const services=[['Barba',20,'15 min'],['Bigode',10,'15 min'],['Cabelo + Barba',55,'45 min'],['Cabelo + Barba + Sobrancelha',65,'45 min'],['Cabelo + Sobrancelha',45,'45 min'],['Sobrancelha',10,'15 min'],['Hidratação Capilar',10,'15 min'],['Limpeza de Pele',20,'15 min'],['Relaxamento Capilar',20,'15 min'],['Luzes',100,'60 min'],['Platinado',125,'60 min'],['Pacote Bronze',100,'45 min'],['Pacote Prata',115,'45 min'],['Pacote Ouro',130,'45 min']];
const professionals=[['João Júnior','Barbeiro e especialista em cortes'],['Profissional 02','Cortes, barba e acabamento'],['Profissional 03','Barbearia e cuidados capilares']];
const state={tab:'services',sort:'value',slide:0};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function render(){const q=($('#search').value||'').toLowerCase(),box=$('#dynamicContent');let title='Serviços',html='';
if(state.tab==='services'){let data=services.filter(x=>x[0].toLowerCase().includes(q));state.sort==='value'?data.sort((a,b)=>a[1]-b[1]):data.sort((a,b)=>a[0].localeCompare(b[0]));html=data.length?data.map((s,i)=>`<article class="service"><div class="service-main"><div class="service-icon">${s[0][0]}</div><div><h3>${s[0]}</h3><div class="meta">◷ ${s[2]}</div></div></div><div><div class="price">${money(s[1])}</div><button class="book-small" data-service="${i}">Agendar</button></div></article>`).join(''):'<div class="empty">Nenhum serviço encontrado.</div>'}
else if(state.tab==='professionals'){title='Profissionais';const data=professionals.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q));html=data.length?data.map(p=>`<article class="professional"><div class="pro-photo">${p[0].split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h3>${p[0]}</h3><p>${p[1]}</p></div></article>`).join(''):'<div class="empty">Nenhum profissional encontrado.</div>'}
else{title=state.tab==='loyalty'?'Fidelidade':state.tab==='products'?'Produtos':'Pacotes';const msg=state.tab==='loyalty'?'Nenhum programa de fidelidade disponível.':state.tab==='products'?'Nenhum produto encontrado.':'Nenhum pacote encontrado.';html=`<div class="empty">${msg}<br><small>Esta área está pronta para receber seus dados.</small></div>`}
$('#sectionTitle').textContent=title;$('#search').placeholder=state.tab==='services'?'Pesquisar serviços':`Pesquisar ${title.toLowerCase()}`;box.innerHTML=html;$$('.book-small').forEach(b=>b.onclick=()=>openModal());}
function openModal(){const modal=$('#modal');$('#modalServices').innerHTML=services.map((s,i)=>`<div class="modal-item"><div><strong>${s[0]}</strong><div class="meta">${money(s[1])} · ${s[2]}</div></div><button data-i="${i}">Selecionar</button></div>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');$$('.modal-item button').forEach(b=>b.onclick=()=>{const s=services[+b.dataset.i];alert(`Serviço selecionado: ${s[0]} — ${money(s[1])}.\n\nConecte aqui o WhatsApp ou sistema de agendamento.`)});}
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');state.tab=t.dataset.tab;render()});
$('#search').addEventListener('input',render);$('#sortBtn').onclick=()=>{state.sort=state.sort==='value'?'name':'value';$('#sortBtn span').textContent=state.sort==='value'?'Valor':'Nome';render()};$('#bookingBtn').onclick=openModal;$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};
$('#heartBtn').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♡'?'♥':'♡';e.currentTarget.style.color=e.currentTarget.textContent==='♥'?'#ff6b00':''};
$('#copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText('');$('#copyBtn').textContent='Copiado!';setTimeout(()=>$('#copyBtn').textContent='Copiar',1500)}catch{alert('Não foi possível copiar automaticamente.')}};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');const l=document.body.classList.contains('light');document.documentElement.style.setProperty('--bg',l?'#f5f5f5':'#0a0a0a');document.documentElement.style.setProperty('--surface',l?'#fff':'#151515');document.documentElement.style.setProperty('--text',l?'#111':'#f6f6f6');document.documentElement.style.setProperty('--muted',l?'#666':'#a6a6a6');$('#themeBtn').textContent=l?'☀':'☾'};
const slides=['JO-O JÚNIOR','CORTE • BARBA','ESTILO • PRECISÃO'];function slide(n){state.slide=(state.slide+n+slides.length)%slides.length;$('#galleryMain').innerHTML=`<span>${slides[state.slide]}</span><small>BARBEARIA</small>`;$$('.dots i').forEach((d,i)=>d.classList.toggle('active',i===state.slide))}$('#prev').onclick=()=>slide(-1);$('#next').onclick=()=>slide(1);$('#dots').innerHTML=slides.map((_,i)=>`<i class="${i?'':'active'}"></i>`).join('');$('#bottomSearch').onclick=()=>{$('#search').focus();window.scrollTo({top:document.querySelector('.content').offsetTop-50,behavior:'smooth'})};$('#bottomBookings').onclick=openModal;render();